# Generated by Django 5.0.1 on 2024-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Suivi", "0004_tresorerybudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergy",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parking",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tresorerycompta",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tresorerycompta",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BILL_TO_DO", "Facture à faire"),
                    ("WAITING", "En attente de payement"),
                    ("TO_PAY", "A payer"),
                    ("PAYED", "Payé"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tresorerybudget",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHF", "CHF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("JPY", "JPY"),
                ],
                default="CHF",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tresorerycompta",
            name="currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHF", "CHF"),
                    ("EUR", "EUR"),
                    ("USD", "USD"),
                    ("JPY", "JPY"),
                ],
                default="CHF",
                max_length=10,
                null=True,
            ),
        ),
    ]
